### ISSUE TITLE
后端接口http://123.56.149.216:8080是不是有问题啊，运行项目访问页面直接报错400

### ISSUE THREAD

**Issue by mebest100** [Frankozay/react_travel#1]
后端接口http://123.56.149.216:8080是不是有问题啊，运行项目访问页面直接报错400，查看网络请求也是错误，感觉应该是后端端口有问题，请问最新的后端接口地址是多少呢

**Comment by Frankozay** [comment]
请问是否在csdn提出相同问题？已在csdn回复
